// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class AuthRoleConfiguration : IEntityTypeConfiguration<AuthRole>
    {
        public void Configure(EntityTypeBuilder<AuthRole> entity)
        {
            entity.HasKey(e => e.No).HasName("PRIMARY");

            entity.Property(e => e.No).HasComment("流水號");
            entity.Property(e => e.Code).HasComment("角色代碼");
            entity.Property(e => e.DeleteAt).HasComment("刪除");
            entity.Property(e => e.Global).HasComment("是否全域");
            entity.Property(e => e.Id).HasComment("角色ID");
            entity.Property(e => e.IsEnabled).HasComment("啟用");
            entity.Property(e => e.Name).HasComment("角色名稱");

            entity.HasMany(d => d.SysMenu).WithMany(p => p.AuthRole)
                .UsingEntity<Dictionary<string, object>>(
                    "AuthRoleMenu",
                    r => r.HasOne<SysMenu>().WithMany()
                        .HasPrincipalKey("Id")
                        .HasForeignKey("SysMenuId")
                        .HasConstraintName("AuthRoleMenu_ibfk_2"),
                    l => l.HasOne<AuthRole>().WithMany()
                        .HasPrincipalKey("Id")
                        .HasForeignKey("AuthRoleId")
                        .HasConstraintName("AuthRoleMenu_ibfk_1"),
                    j =>
                    {
                        j.HasKey("AuthRoleId", "SysMenuId")
                            .HasName("PRIMARY")
                            .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });
                        j.HasIndex(new[] { "SysMenuId" }, "SysMenuId");
                        j.IndexerProperty<Guid>("AuthRoleId").HasComment("角色ID");
                        j.IndexerProperty<Guid>("SysMenuId").HasComment("選單ID");
                    });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AuthRole> entity);
    }
}
