// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class AuthRoleConfiguration : IEntityTypeConfiguration<AuthRole>
    {
        public void Configure(EntityTypeBuilder<AuthRole> entity)
        {
            entity.HasKey(e => e.No).HasName("PRIMARY");

            entity.Property(e => e.No).HasComment("流水號");
            entity.Property(e => e.Code).HasComment("角色代碼");
            entity.Property(e => e.DeleteAt).HasComment("刪除");
            entity.Property(e => e.Id).HasComment("角色ID");
            entity.Property(e => e.IsEnabled).HasComment("啟用");
            entity.Property(e => e.Name).HasComment("角色名稱");


            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AuthRole> entity);
    }
}
