// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class AuthForgetConfiguration : IEntityTypeConfiguration<AuthForget>
    {
        public void Configure(EntityTypeBuilder<AuthForget> entity)
        {
            entity.HasKey(e => e.No).HasName("PRIMARY");

            entity.Property(e => e.No).HasComment("流水號");
            entity.Property(e => e.ExpiresAt).HasComment("有效時間");
            entity.Property(e => e.Id).HasComment("忘記密碼ID");
            entity.Property(e => e.IsUsed).HasComment("是否使用");
            entity.Property(e => e.UserId).HasComment("使用者ID");

            entity.HasOne(d => d.User).WithMany(p => p.AuthForget)
                .HasPrincipalKey(p => p.Id)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("AuthForget_ibfk_1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AuthForget> entity);
    }
}
