// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class AuthUserConfiguration : IEntityTypeConfiguration<AuthUser>
    {
        public void Configure(EntityTypeBuilder<AuthUser> entity)
        {
            entity.HasKey(e => e.No).HasName("PRIMARY");
            entity.HasAlternateKey(e => e.Id);
            entity.Property(e => e.No)
                .ValueGeneratedOnAdd()     
                .HasComment("流水號");
            entity.Property(e => e.Account).HasComment("帳號");
            entity.Property(e => e.Card).HasComment("卡號");
            entity.Property(e => e.CreateAt).HasComment("建立時間	");
            entity.Property(e => e.DeleteAt).HasComment("刪除");
            entity.Property(e => e.DepartmentId).HasComment("單位");
            entity.Property(e => e.Email).HasComment("電子信箱	");
            entity.Property(e => e.Id).HasComment("使用者ID	");
            entity.Property(e => e.IsEnabled).HasComment("啟用");
            entity.Property(e => e.Name).HasComment("名稱");
            entity.Property(e => e.Password).HasComment("密碼");
            entity.Property(e => e.PasswordHash).HasComment("密碼雜湊");
            entity.Property(e => e.PasswordSalt).HasComment("密碼鹽值");

            entity.HasOne(d => d.Department).WithMany(p => p.AuthUser)
                .HasPrincipalKey(p => p.Id)
                .HasForeignKey(d => d.DepartmentId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("AuthUser_ibfk_1");

            entity.HasMany(d => d.AuthRole).WithMany(p => p.AuthUser)
    .UsingEntity<Dictionary<string, object>>(
        "AuthUserRole",
        r => r.HasOne<AuthRole>().WithMany()
            .HasPrincipalKey("Id")  // ✅ 保持 Id（Guid）
            .HasForeignKey("AuthRoleId")
            .HasConstraintName("AuthUserRole_ibfk_2"),
        l => l.HasOne<AuthUser>().WithMany()
            .HasPrincipalKey("Id")  // ✅ 改成 Id（Guid），不是 No
            .HasForeignKey("AuthUserId")
            .HasConstraintName("AuthUserRole_ibfk_1"),
        j =>
        {
            j.HasKey("AuthUserId", "AuthRoleId")
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });
            j.HasIndex(new[] { "AuthRoleId" }, "AuthRoleId");
            j.IndexerProperty<Guid>("AuthUserId").HasComment("使用者ID");   // ✅ Guid
            j.IndexerProperty<Guid>("AuthRoleId").HasComment("角色ID");     // ✅ Guid
        });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AuthUser> entity);
    }
}
