// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class ConferenceUserConfiguration : IEntityTypeConfiguration<ConferenceUser>
    {
        public void Configure(EntityTypeBuilder<ConferenceUser> entity)
        {
            entity.HasKey(e => new { e.ConferenceId, e.UserId })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity.Property(e => e.ConferenceId).HasComment("會議ID");
            entity.Property(e => e.UserId).HasComment("使用者ID");
            entity.Property(e => e.IsAttendees).HasComment("與會人員");
            entity.Property(e => e.IsHost).HasComment("主持人");
            entity.Property(e => e.IsRecorder).HasComment("會議記錄");

            entity.HasOne(d => d.Conference).WithMany(p => p.ConferenceUser)
                .HasPrincipalKey(p => p.Id)
                .HasForeignKey(d => d.ConferenceId)
                .HasConstraintName("ConferenceUser_ibfk_1");

            entity.HasOne(d => d.User).WithMany(p => p.ConferenceUser)
                .HasPrincipalKey(p => p.Id)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("ConferenceUser_ibfk_2");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ConferenceUser> entity);
    }
}
