// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TASA.Models;
using TASA.Models.Enums;

namespace TASA.Models.Configurations;

public partial class ConferencePaymentProofConfiguration : IEntityTypeConfiguration<ConferencePaymentProof>
{
    public void Configure(EntityTypeBuilder<ConferencePaymentProof> entity)
    {
        entity.HasKey(e => e.Id).HasName("PRIMARY");

        entity.ToTable("ConferencePaymentProof");


        entity.HasIndex(e => e.ConferenceId, "idx_conference_id");

        entity.HasIndex(e => e.Status, "idx_status");

        entity.HasIndex(e => e.UploadedBy, "idx_uploaded_by");

        entity.HasIndex(e => e.ReviewedBy, "idx_reviewed_by");

        entity.Property(e => e.Id)
            .IsRequired()
            .HasColumnType("char(36)")
            .HasComment("憑證ID");

        entity.Property(e => e.ConferenceId)
            .IsRequired()
            .HasColumnType("char(36)")
            .HasComment("會議ID");

        entity.Property(e => e.FilePath)
            .IsRequired()
            .HasMaxLength(500)
            .HasComment("檔案路徑");

        entity.Property(e => e.FileName)
            .IsRequired()
            .HasMaxLength(255)
            .HasComment("檔案名稱");

        entity.Property(e => e.PaymentType)
            .HasMaxLength(50)
            .HasComment("付款方式 (臨櫃/匯款)");

        entity.Property(e => e.LastFiveDigits)
            .HasMaxLength(5)
            .HasComment("轉帳末五碼");

        entity.Property(e => e.TransferAmount)
            .HasColumnType("int(11)")
            .HasComment("轉帳金額");

        entity.Property(e => e.TransferAt)
            .HasColumnType("datetime")
            .HasComment("轉帳時間");

        entity.Property(e => e.Note)
            .HasColumnType("text")
            .HasComment("備註");

        entity.Property(e => e.Status)
    .HasColumnType("tinyint(1) unsigned")
    .HasDefaultValue(ProofStatus.PendingReview)
    .HasComment("審核狀態 (0=待審核, 1=已批准, 2=已退回)");

        entity.Property(e => e.RejectReason)
            .HasColumnType("text")
            .HasComment("退回原因");

        entity.Property(e => e.UploadedAt)
            .HasColumnType("datetime")
            .HasComment("上傳時間");

        entity.Property(e => e.UploadedBy)
            .IsRequired()
            .HasColumnType("char(36)")
            .HasComment("上傳者");

        entity.Property(e => e.ReviewedAt)
            .HasColumnType("datetime")
            .HasComment("審核時間");

        entity.Property(e => e.ReviewedBy)
            .HasColumnType("char(36)")
            .HasComment("審核者");

        entity.Property(e => e.DeleteAt)
            .HasColumnType("datetime")
            .HasComment("刪除時間");

        entity.HasOne(d => d.Conference)
            .WithMany(p => p.ConferencePaymentProofs)
            .HasPrincipalKey(p => p.Id)
            .HasForeignKey(d => d.ConferenceId)
            .OnDelete(DeleteBehavior.Cascade)
            .HasConstraintName("ConferencePaymentProof_ibfk_1");

        entity.HasOne(d => d.UploadedByNavigation)
            .WithMany(p => p.ConferencePaymentProofUploadedBy)
            .HasPrincipalKey(p => p.Id)
            .HasForeignKey(d => d.UploadedBy)
            .OnDelete(DeleteBehavior.Restrict)
            .HasConstraintName("ConferencePaymentProof_ibfk_2");

        entity.HasOne(d => d.ReviewedByNavigation)
            .WithMany(p => p.ConferencePaymentProofReviewedBy)
            .HasPrincipalKey(p => p.Id)
            .HasForeignKey(d => d.ReviewedBy)
            .OnDelete(DeleteBehavior.Restrict)
            .HasConstraintName("ConferencePaymentProof_ibfk_3");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<ConferencePaymentProof> entity);
}