// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;
using TASA.Models.Enums;

namespace TASA.Models.Configurations
{
    public partial class ConferenceConfiguration : IEntityTypeConfiguration<Conference>
    {
        public void Configure(EntityTypeBuilder<Conference> entity)
        {
            entity.HasKey(e => e.No).HasName("PRIMARY");

            entity.Property(e => e.No).HasComment("流水號");
            entity.Property(e => e.AgentBy).HasComment("協助報到者");
            entity.Property(e => e.CheckinAt).HasComment("報到時間");
            entity.Property(e => e.CheckinBy).HasComment("報到者");
            entity.Property(e => e.CreateAt).HasComment("建立時間");
            entity.Property(e => e.CreateBy).HasComment("建立者");
            entity.Property(e => e.UpdateAt)
    .HasColumnType("datetime")
    .HasComment("更新時間");
            entity.Property(e => e.DeleteAt).HasComment("刪除");
            entity.Property(e => e.Description).HasComment("會議內容");
            entity.Property(e => e.DurationHH).HasComment("持續時間(小時)");
            entity.Property(e => e.DurationSS).HasComment("持續時間(分鐘)");
            entity.Property(e => e.Email).HasComment("電子郵件通知信箱群");
            entity.Property(e => e.EndTime).HasComment("結束時間 (由 ConferenceRoomSlot 決定，可為 NULL)"); // ✅ 修改註釋
            entity.Property(e => e.FinishTime).HasComment("實際結束時間");
            entity.Property(e => e.Id).HasComment("會議ID");
            entity.Property(e => e.MCU).HasComment("連線選項");
            entity.Property(e => e.Name).HasComment("名稱");
            entity.Property(e => e.RRule).HasComment("重複(RFC5545)");
            entity.Property(e => e.Recording).HasComment("錄製");
            entity.Property(e => e.RecurrenceId).HasComment("重複會議父ID");
            entity.Property(e => e.StartTime).HasComment("開始時間 (由 ConferenceRoomSlot 決定，可為 NULL)"); // ✅ 修改註釋
            entity.Property(e => e.Status)
                .HasColumnType("tinyint(1) unsigned")
                .HasDefaultValue(null)
                .HasComment("會議狀態 (1=已排程, 2=進行中, 3=已完成, 4=未出席)");
            entity.Property(e => e.UsageType).HasComment("會議種類 (1:一般 2:視訊)");

            // ✅ 新增預約狀態欄位
            entity.Property(e => e.ReservationStatus)
    .HasColumnType("tinyint(1) unsigned")
    .HasDefaultValue(ReservationStatus.PendingApproval) // ✅ 改這裡
    .HasComment("預約狀態 (1=待審核, 2=待繳費, 3=預約成功, 4=審核拒絕, 5=已取消)"); // ✅ 改註解

            entity.Property(e => e.RejectReason)
                .HasColumnType("text")
                .HasComment("拒絕原因");

            entity.Property(e => e.ReviewedAt)
                .HasColumnType("datetime")
                .HasComment("審核時間");

            entity.Property(e => e.ReviewedBy)
                .HasComment("審核者");

            entity.Property(e => e.ApprovedAt)
                .HasColumnType("datetime")
                .HasComment("批准時間");

            entity.Property(e => e.PaymentDeadline)
                .HasColumnType("datetime")
                .HasComment("繳費期限");

            // ✅ 付費相關欄位
            entity.Property(e => e.PaymentMethod)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("付費方式");

            entity.Property(e => e.PaymentStatus)
    .HasColumnType("tinyint(1) unsigned")
    .HasDefaultValue(PaymentStatus.Unpaid) // ✅ 改這裡
    .HasComment("付款狀態 (1=未付款, 2=待查帳, 3=已收款, 4=待重新上傳)"); // ✅ 改註解

            entity.Property(e => e.PaymentNote)
                .HasMaxLength(255)
                .HasComment("付款備註");

            entity.Property(e => e.PaidAt)
                .HasColumnType("datetime")
                .HasComment("付款日期");

            entity.Property(e => e.DepartmentCode)
                .HasMaxLength(50)
                .HasComment("部門代碼");

            // ✅ 費用欄位
            entity.Property(e => e.RoomCost)
                .HasColumnType("int(11)")
                .HasDefaultValueSql("'0'")
                .HasComment("會議室費用");

            entity.Property(e => e.EquipmentCost)
                .HasColumnType("int(11)")
                .HasDefaultValueSql("'0'")
                .HasComment("設備費用");

            entity.Property(e => e.BoothCost)
                .HasColumnType("int(11)")
                .HasDefaultValueSql("'0'")
                .HasComment("攤位費用");

            entity.Property(e => e.TotalAmount)
                .HasColumnType("int(11)")
                .HasDefaultValueSql("'0'")
                .HasComment("總金額");

            // ✅ 新增索引
            entity.HasIndex(new[] { nameof(Conference.ReservationStatus), nameof(Conference.CreateAt) }, "idx_reservation_status");

            // ===============================
            // Relationships
            // ===============================

            entity.HasOne(d => d.CreateByNavigation).WithMany(p => p.Conference)
                .HasPrincipalKey(p => p.Id)
                .HasForeignKey(d => d.CreateBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Conference_ibfk_2");

            entity.HasOne(d => d.StatusNavigation).WithMany(p => p.Conference)
                .HasForeignKey(d => d.Status)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("Conference_ibfk_1");

            // ✅ 新增：Conference → ConferenceRoomSlot 的關係
            entity.HasMany(d => d.ConferenceRoomSlots)
                .WithOne(s => s.Conference)
                .HasForeignKey(s => s.ConferenceId)
                .HasPrincipalKey(c => c.Id)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_slot_conf");

            entity.HasMany(d => d.Department).WithMany(p => p.Conference)
                .UsingEntity<Dictionary<string, object>>(
                    "ConferenceDepartment",
                    r => r.HasOne<SysDepartment>().WithMany()
                        .HasPrincipalKey("Id")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("ConferenceDepartment_ibfk_2"),
                    l => l.HasOne<Conference>().WithMany()
                        .HasPrincipalKey("Id")
                        .HasForeignKey("ConferenceId")
                        .HasConstraintName("ConferenceDepartment_ibfk_1"),
                    j =>
                    {
                        j.HasKey("ConferenceId", "DepartmentId")
                            .HasName("PRIMARY")
                            .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });
                        j.HasIndex(new[] { "DepartmentId" }, "ConferencesDepartments_ibfk_2");
                    });

            entity.HasMany(d => d.Ecs).WithMany(p => p.Conference)
                .UsingEntity<Dictionary<string, Guid>>(
                    "ConferenceEcs",
                    r => r.HasOne<Ecs>().WithMany()
                        .HasPrincipalKey("Id")
                        .HasForeignKey("EcsId")
                        .HasConstraintName("ConferenceEcs_ibfk_2"),
                    l => l.HasOne<Conference>().WithMany()
                        .HasPrincipalKey("Id")
                        .HasForeignKey("ConferenceId")
                        .HasConstraintName("ConferenceEcs_ibfk_1"),
                    j =>
                    {
                        j.HasKey("ConferenceId", "EcsId")
                            .HasName("PRIMARY")
                            .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });
                        j.HasIndex(new[] { "EcsId" }, "ConferenceEcs_ibfk_2");
                        j.IndexerProperty<Guid>("ConferenceId").HasComment("會議ID");
                        j.IndexerProperty<Guid>("EcsId").HasComment("情境ID");
                    });

            entity.HasMany(d => d.Room).WithMany(p => p.Conference)
                .UsingEntity<Dictionary<string, object>>(
                    "ConferenceRoom",
                    r => r.HasOne<SysRoom>().WithMany()
                        .HasPrincipalKey("Id")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("ConferenceRoom_ibfk_2"),
                    l => l.HasOne<Conference>().WithMany()
                        .HasPrincipalKey("Id")
                        .HasForeignKey("ConferenceId")
                        .HasConstraintName("ConferenceRoom_ibfk_1"),
                    j =>
                    {
                        j.HasKey("ConferenceId", "RoomId")
                            .HasName("PRIMARY")
                            .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });
                        j.HasIndex(new[] { "RoomId" }, "ConferencesRooms_ibfk_2");
                        j.IndexerProperty<Guid>("ConferenceId").HasComment("會議ID");
                        j.IndexerProperty<Guid>("RoomId").HasComment("會議室ID");
                    });
            entity.Property(e => e.CancelledAt)
                .HasColumnType("datetime")
                .HasComment("取消時間");

            entity.Property(e => e.CancelledBy)
                .HasComment("取消者");

            // ✅ 如果有 Navigation Property,也要加上關係設定
            entity.HasOne(d => d.CancelledByNavigation)
                .WithMany()
                .HasPrincipalKey(p => p.Id)
                .HasForeignKey(d => d.CancelledBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("Conference_ibfk_3");


            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Conference> entity);
    }
}