// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class ConferenceConfiguration : IEntityTypeConfiguration<Conference>
    {
        public void Configure(EntityTypeBuilder<Conference> entity)
        {
            entity.HasKey(e => e.No).HasName("PRIMARY");

            entity.Property(e => e.No).HasComment("流水號");
            entity.Property(e => e.AgentBy).HasComment("協助報到者");
            entity.Property(e => e.CheckinAt).HasComment("報到時間");
            entity.Property(e => e.CheckinBy).HasComment("報到者");
            entity.Property(e => e.CreateAt).HasComment("建立時間");
            entity.Property(e => e.CreateBy).HasComment("建立者");
            entity.Property(e => e.DeleteAt).HasComment("刪除");
            entity.Property(e => e.Description).HasComment("會議內容");
            entity.Property(e => e.DurationHH).HasComment("持續時間(小時)");
            entity.Property(e => e.DurationSS).HasComment("持續時間(分鐘)");
            entity.Property(e => e.Email).HasComment("電子郵件通知信箱群");
            entity.Property(e => e.EndTime).HasComment("結束時間");
            entity.Property(e => e.FinishTime).HasComment("實際結束時間");
            entity.Property(e => e.Id).HasComment("會議ID");
            entity.Property(e => e.MCU).HasComment("連線選項");
            entity.Property(e => e.Name).HasComment("名稱");
            entity.Property(e => e.RRule).HasComment("重複(RFC5545)");
            entity.Property(e => e.Recording).HasComment("錄製");
            entity.Property(e => e.RecurrenceId).HasComment("重複會議父ID");
            entity.Property(e => e.StartTime).HasComment("開始時間");
            entity.Property(e => e.PaymentMethod)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("付費方式");

            entity.Property(e => e.PaymentStatus)
                .HasColumnType("int(11)")
                .HasDefaultValueSql("'1'")
                .HasComment("付款狀態");

            entity.Property(e => e.PaymentNote)
                .HasMaxLength(255)
                .HasComment("付款備註");

            entity.Property(e => e.PaidAt)
                .HasColumnType("datetime")
                .HasComment("付款日期");

            entity.Property(e => e.DepartmentCode)
                .HasMaxLength(50)
                .HasComment("部門代碼");

            entity.Property(e => e.RoomCost)
                .HasColumnType("int(11)")
                .HasDefaultValueSql("'0'")
                .HasComment("會議室費用");

            entity.Property(e => e.EquipmentCost)
                .HasColumnType("int(11)")
                .HasDefaultValueSql("'0'")
                .HasComment("設備費用");

            entity.Property(e => e.BoothCost)
                .HasColumnType("int(11)")
                .HasDefaultValueSql("'0'")
                .HasComment("攤位費用");

            entity.Property(e => e.TotalAmount)
                .HasColumnType("int(11)")
                .HasDefaultValueSql("'0'")
                .HasComment("總金額");
            entity.Property(e => e.Status)
                .HasDefaultValueSql("'1'")
                .HasComment("狀態");
            entity.Property(e => e.UsageType).HasComment("會議種類 (1:一般 2:視訊)");

            entity.HasOne(d => d.CreateByNavigation).WithMany(p => p.Conference)
                .HasPrincipalKey(p => p.Id)
                .HasForeignKey(d => d.CreateBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Conference_ibfk_2");

            entity.HasOne(d => d.StatusNavigation).WithMany(p => p.Conference)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Conference_ibfk_1");

            entity.HasMany(d => d.Department).WithMany(p => p.Conference)
                .UsingEntity<Dictionary<string, object>>(
                    "ConferenceDepartment",
                    r => r.HasOne<SysDepartment>().WithMany()
                        .HasPrincipalKey("Id")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("ConferenceDepartment_ibfk_2"),
                    l => l.HasOne<Conference>().WithMany()
                        .HasPrincipalKey("Id")
                        .HasForeignKey("ConferenceId")
                        .HasConstraintName("ConferenceDepartment_ibfk_1"),
                    j =>
                    {
                        j.HasKey("ConferenceId", "DepartmentId")
                            .HasName("PRIMARY")
                            .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });
                        j.HasIndex(new[] { "DepartmentId" }, "ConferencesDepartments_ibfk_2");
                    });

            entity.HasMany(d => d.Ecs).WithMany(p => p.Conference)
                .UsingEntity<Dictionary<string, Guid>>(
                    "ConferenceEcs",
                    r => r.HasOne<Ecs>().WithMany()
                        .HasPrincipalKey("Id")
                        .HasForeignKey("EcsId")
                        .HasConstraintName("ConferenceEcs_ibfk_2"),
                    l => l.HasOne<Conference>().WithMany()
                        .HasPrincipalKey("Id")
                        .HasForeignKey("ConferenceId")
                        .HasConstraintName("ConferenceEcs_ibfk_1"),
                    j =>
                    {
                        j.HasKey("ConferenceId", "EcsId")
                            .HasName("PRIMARY")
                            .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });
                        j.HasIndex(new[] { "EcsId" }, "ConferenceEcs_ibfk_2");
                        j.IndexerProperty<Guid>("ConferenceId").HasComment("會議ID");
                        j.IndexerProperty<Guid>("EcsId").HasComment("情境ID");
                    });

            entity.HasMany(d => d.Room).WithMany(p => p.Conference)
                .UsingEntity<Dictionary<string, object>>(
                    "ConferenceRoom",
                    r => r.HasOne<SysRoom>().WithMany()
                        .HasPrincipalKey("Id")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("ConferenceRoom_ibfk_2"),
                    l => l.HasOne<Conference>().WithMany()
                        .HasPrincipalKey("Id")
                        .HasForeignKey("ConferenceId")
                        .HasConstraintName("ConferenceRoom_ibfk_1"),
                    j =>
                    {
                        j.HasKey("ConferenceId", "RoomId")
                            .HasName("PRIMARY")
                            .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });
                        j.HasIndex(new[] { "RoomId" }, "ConferencesRooms_ibfk_2");
                        j.IndexerProperty<Guid>("ConferenceId").HasComment("會議ID");
                        j.IndexerProperty<Guid>("RoomId").HasComment("會議室ID");
                    });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Conference> entity);
    }
}
