// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class ConferenceTemplateConfiguration : IEntityTypeConfiguration<ConferenceTemplate>
    {
        public void Configure(EntityTypeBuilder<ConferenceTemplate> entity)
        {
            entity.HasKey(e => e.No).HasName("PRIMARY");

            entity.Property(e => e.No).HasComment("流水號");
            entity.Property(e => e.CreateAt).HasComment("建立時間");
            entity.Property(e => e.CreateBy).HasComment("建立者");
            entity.Property(e => e.DeleteAt).HasComment("刪除");
            entity.Property(e => e.Description).HasComment("會議內容");
            entity.Property(e => e.DurationHH).HasComment("持續時間(小時)");
            entity.Property(e => e.DurationSS).HasComment("持續時間(分鐘)");
            entity.Property(e => e.Email).HasComment("電子郵件通知信箱群");
            entity.Property(e => e.Id).HasComment("會議ID");
            entity.Property(e => e.MCU).HasComment("連線選項");
            entity.Property(e => e.Name).HasComment("名稱");
            entity.Property(e => e.RRule).HasComment("重複(RFC5545)");
            entity.Property(e => e.Recording).HasComment("錄製");
            entity.Property(e => e.UsageType).HasComment("會議種類 (1:一般 2:視訊)");

            entity.HasMany(d => d.Department).WithMany(p => p.ConferenceNavigation)
                .UsingEntity<Dictionary<string, object>>(
                    "ConferenceTemplateDepartment",
                    r => r.HasOne<SysDepartment>().WithMany()
                        .HasPrincipalKey("Id")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("ConferenceTemplateDepartment_ibfk_2"),
                    l => l.HasOne<ConferenceTemplate>().WithMany()
                        .HasPrincipalKey("Id")
                        .HasForeignKey("ConferenceId")
                        .HasConstraintName("ConferenceTemplateDepartment_ibfk_1"),
                    j =>
                    {
                        j.HasKey("ConferenceId", "DepartmentId")
                            .HasName("PRIMARY")
                            .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });
                        j.HasIndex(new[] { "DepartmentId" }, "DepartmentsId");
                    });

            entity.HasMany(d => d.Room).WithMany(p => p.ConferenceNavigation)
                .UsingEntity<Dictionary<string, object>>(
                    "ConferenceTemplateRoom",
                    r => r.HasOne<SysRoom>().WithMany()
                        .HasPrincipalKey("Id")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("ConferenceTemplateRoom_ibfk_2"),
                    l => l.HasOne<ConferenceTemplate>().WithMany()
                        .HasPrincipalKey("Id")
                        .HasForeignKey("ConferenceId")
                        .HasConstraintName("ConferenceTemplateRoom_ibfk_1"),
                    j =>
                    {
                        j.HasKey("ConferenceId", "RoomId")
                            .HasName("PRIMARY")
                            .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });
                        j.HasIndex(new[] { "RoomId" }, "RoomsId");
                        j.IndexerProperty<Guid>("ConferenceId").HasComment("會議ID");
                        j.IndexerProperty<Guid>("RoomId").HasComment("會議室ID");
                    });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ConferenceTemplate> entity);
    }
}
