// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class ConferenceWebexConfiguration : IEntityTypeConfiguration<ConferenceWebex>
    {
        public void Configure(EntityTypeBuilder<ConferenceWebex> entity)
        {
            entity.HasKey(e => e.ConferencesId).HasName("PRIMARY");

            entity.Property(e => e.ConferencesId)
                .ValueGeneratedOnAdd()
                .HasComment("UCMS會議ID");
            entity.Property(e => e.CallInNumber).HasComment("撥入號碼");
            entity.Property(e => e.DeleteAt).HasComment("刪除");
            entity.Property(e => e.HostKey).HasComment("主持人金鑰");
            entity.Property(e => e.Id).HasComment("meetingId");
            entity.Property(e => e.MeetingNumber).HasComment("會議號碼");
            entity.Property(e => e.Password).HasComment("會議密碼");
            entity.Property(e => e.SipAddress).HasComment("SIP");
            entity.Property(e => e.WebLink).HasComment("會議連結");
            entity.Property(e => e.WebexId).HasComment("Webex");

            entity.HasOne(d => d.Conferences).WithOne(p => p.ConferenceWebex)
                .HasPrincipalKey<Conference>(p => p.Id)
                .HasForeignKey<ConferenceWebex>(d => d.ConferencesId)
                .HasConstraintName("ConferenceWebex_ibfk_1");

            entity.HasOne(d => d.Webex).WithMany(p => p.ConferenceWebex)
                .HasPrincipalKey(p => p.Id)
                .HasForeignKey(d => d.WebexId)
                .HasConstraintName("ConferenceWebex_ibfk_2");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ConferenceWebex> entity);
    }
}
