// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TASA.Models;

namespace TASA.Models.Configurations;

public partial class ConferenceEquipmentConfiguration : IEntityTypeConfiguration<ConferenceEquipment>
{
    public void Configure(EntityTypeBuilder<ConferenceEquipment> entity)
    {
        entity.HasKey(e => e.Id).HasName("PRIMARY");

        entity.ToTable("ConferenceEquipment");

        entity.HasIndex(e => e.ConferenceId, "idx_conference");

        entity.HasIndex(e => new { e.EquipmentId, e.SlotDate, e.StartTime, e.EndTime }, "idx_equipment_date_time");

        entity.Property(e => e.Id)
            .HasColumnType("char(36)")
            .HasComment("ID");

        entity.Property(e => e.ConferenceId)
            .IsRequired()
            .HasColumnType("char(36)")
            .HasComment("會議ID");

        entity.Property(e => e.EquipmentId)
            .IsRequired()
            .HasColumnType("char(36)")
            .HasComment("設備ID (包含攤位)");

        entity.Property(e => e.EquipmentType)
            .IsRequired()
            .HasMaxLength(1)
            .HasComment("類型 8=公有設備 9=攤位");

        entity.Property(e => e.EquipmentName)
            .IsRequired()
            .HasMaxLength(100)
            .HasComment("設備名稱快照");

        entity.Property(e => e.EquipmentPrice)
            .HasColumnType("int(11)")
            .HasDefaultValueSql("'0'")
            .HasComment("設備價格快照");

        entity.Property(e => e.SlotDate)
            .IsRequired()
            .HasComment("使用日期");

        entity.Property(e => e.StartTime)
            .IsRequired()
            .HasComment("開始時間");

        entity.Property(e => e.EndTime)
            .IsRequired()
            .HasComment("結束時間");

        entity.Property(e => e.EquipmentStatus)
            .HasColumnType("tinyint")
            .HasDefaultValueSql("'1'")
            .HasComment("狀態: 0=可用 1=鎖定中 2=已預約");

        entity.Property(e => e.LockedAt)
            .HasColumnType("datetime")
            .HasComment("鎖定時間");

        entity.Property(e => e.ReleasedAt)
            .HasColumnType("datetime")
            .HasComment("釋放時間");

        entity.Property(e => e.CreatedAt)
            .HasColumnType("datetime")
            .HasComment("建立時間");

        entity.HasOne(d => d.Conference)
            .WithMany(p => p.ConferenceEquipments)
            .HasPrincipalKey(p => p.Id)
            .HasForeignKey(d => d.ConferenceId)
            .OnDelete(DeleteBehavior.Cascade)
            .HasConstraintName("fk_equipment_conference");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<ConferenceEquipment> entity);
}