// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class EcsConfiguration : IEntityTypeConfiguration<Ecs>
    {
        public void Configure(EntityTypeBuilder<Ecs> entity)
        {
            entity.HasKey(e => e.No).HasName("PRIMARY");

            entity.Property(e => e.No).HasComment("流水號");
            entity.Property(e => e.CreateAt).HasComment("建立時間");
            entity.Property(e => e.CreateBy).HasComment("建立者");
            entity.Property(e => e.DeleteAt).HasComment("刪除時間");
            entity.Property(e => e.Id).HasComment("情境ID");
            entity.Property(e => e.IsEnabled).HasComment("啟用");
            entity.Property(e => e.Macro).HasComment("指令");
            entity.Property(e => e.Name).HasComment("名稱");
            entity.Property(e => e.RoomId).HasComment("會議室ID");

            entity.HasOne(d => d.Room).WithMany(p => p.Ecs)
                .HasPrincipalKey(p => p.Id)
                .HasForeignKey(d => d.RoomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Ecs_ibfk_1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Ecs> entity);
    }
}
