// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class EcsEquipmentConfiguration : IEntityTypeConfiguration<EcsEquipment>
    {
        public void Configure(EntityTypeBuilder<EcsEquipment> entity)
        {
            entity.HasKey(e => new { e.EcsId, e.EquipmentId })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity.Property(e => e.EcsId).HasComment("情境ID");
            entity.Property(e => e.EquipmentId).HasComment("設備ID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EcsEquipment> entity);
    }
}
