// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class EquipmentConfiguration : IEntityTypeConfiguration<Equipment>
    {
        public void Configure(EntityTypeBuilder<Equipment> entity)
        {
            entity.HasKey(e => e.No).HasName("PRIMARY");

            entity.Property(e => e.No).HasComment("流水號");
            entity.Property(e => e.Account).HasComment("帳號");
            entity.Property(e => e.CreateAt).HasComment("建立時間");
            entity.Property(e => e.CreateBy).HasComment("建立者");
            entity.Property(e => e.DeleteAt).HasComment("刪除");
            entity.Property(e => e.Host).HasComment("裝備位置");
            entity.Property(e => e.Id).HasComment("裝備ID");
            entity.Property(e => e.IsEnabled).HasComment("啟用");
            entity.Property(e => e.Name).HasComment("名稱");
            entity.Property(e => e.Password).HasComment("密碼");
            entity.Property(e => e.Port).HasComment("Port");
            entity.Property(e => e.Type).HasComment("裝備類型");

            entity.HasOne(d => d.TypeNavigation).WithMany(p => p.Equipment)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Equipment_ibfk_1");

            // 設備照片路徑
            entity.Property(e => e.ImagePath)
                .HasMaxLength(500)
                .HasComment("設備照片路徑");

            // ✅ 新增：產品型號
            entity.Property(e => e.ProductModel)
                .HasMaxLength(100)
                .HasComment("產品型號");

            // ✅ 修正：租借金額改成 int（整數）
            entity.Property(e => e.RentalPrice)
                .HasDefaultValue(0)
                .HasComment("租借金額（整數，僅限租借類設備）");

            // ✅ 新增：會議室 ID
            entity.Property(e => e.RoomId)
                .HasComment("會議室ID（可為空）");

            // ✅ 新增：會議室關聯
            entity.HasOne(d => d.Room)
                .WithMany(p => p.Equipment)
                .HasForeignKey(d => d.RoomId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("Equipment_ibfk_2");

            // ✅ 新增：分院 ID
            entity.Property(e => e.DepartmentId)
                .HasComment("分院ID（設備所屬分院）");

            // ✅ 新增：分院關聯
            entity.HasOne(d => d.Department)
                .WithMany()
                .HasForeignKey(d => d.DepartmentId)
                .HasPrincipalKey(d => d.Id)  // ✅ 指定使用 Id (Guid) 而不是 No (uint)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("Equipment_ibfk_3");


            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Equipment> entity);
    }
}
