// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class EquipmentConfiguration : IEntityTypeConfiguration<Equipment>
    {
        public void Configure(EntityTypeBuilder<Equipment> entity)
        {
            entity.HasKey(e => e.No).HasName("PRIMARY");

            entity.Property(e => e.No).HasComment("流水號");
            entity.Property(e => e.Account).HasComment("帳號");
            entity.Property(e => e.CreateAt).HasComment("建立時間");
            entity.Property(e => e.CreateBy).HasComment("建立者");
            entity.Property(e => e.DeleteAt).HasComment("刪除");
            entity.Property(e => e.Host).HasComment("裝備位置");
            entity.Property(e => e.Id).HasComment("裝備ID");
            entity.Property(e => e.IsEnabled).HasComment("啟用");
            entity.Property(e => e.Name).HasComment("名稱");
            entity.Property(e => e.Password).HasComment("密碼");
            entity.Property(e => e.Port).HasComment("Port");
            entity.Property(e => e.Type).HasComment("裝備類型");

            entity.HasOne(d => d.TypeNavigation).WithMany(p => p.Equipment)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Equipment_ibfk_1");
            // ✅ 新增：產品型號
            entity.Property(e => e.ProductModel)
                .HasMaxLength(100)
                .HasComment("產品型號");

            // ✅ 新增：租借金額
            entity.Property(e => e.RentalPrice)
                .HasPrecision(10, 2)
                .HasDefaultValue(0)
                .HasComment("租借金額（僅限租借類設備）");
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Equipment> entity);
    }
}
