// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class LogMailConfiguration : IEntityTypeConfiguration<LogMail>
    {
        public void Configure(EntityTypeBuilder<LogMail> entity)
        {
            entity.HasKey(e => e.No).HasName("PRIMARY");

            entity.Property(e => e.No).HasComment("流水號");
            entity.Property(e => e.Address).HasComment("收件者");
            entity.Property(e => e.ClassName).HasComment("觸發Class");
            entity.Property(e => e.EnableSsl).HasComment("SMTP SSL");
            entity.Property(e => e.Exception).HasComment("錯誤資訊");
            entity.Property(e => e.FunctionName).HasComment("觸發Function");
            entity.Property(e => e.Port).HasComment("SMTP PORT");
            entity.Property(e => e.SendTime).HasComment("寄送時間");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LogMail> entity);
    }
}
