// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class LogSysConfiguration : IEntityTypeConfiguration<LogSys>
    {
        public void Configure(EntityTypeBuilder<LogSys> entity)
        {
            entity.HasKey(e => e.No).HasName("PRIMARY");

            entity.Property(e => e.No).HasComment("流水號");
            entity.Property(e => e.Info).HasComment("訊息");
            entity.Property(e => e.InfoType).HasComment("類型");
            entity.Property(e => e.Ip).HasComment("IP");
            entity.Property(e => e.Time).HasComment("時間");
            entity.Property(e => e.UserId).HasComment("使用者ID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LogSys> entity);
    }
}
