// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class LogWebexConfiguration : IEntityTypeConfiguration<LogWebex>
    {
        public void Configure(EntityTypeBuilder<LogWebex> entity)
        {
            entity.HasKey(e => e.No).HasName("PRIMARY");

            entity.HasOne(d => d.Conference).WithMany(p => p.LogWebex)
                .HasPrincipalKey(p => p.Id)
                .HasForeignKey(d => d.ConferenceId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("LogWebex_ibfk_1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LogWebex> entity);
    }
}
