// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class SysDepartmentConfiguration : IEntityTypeConfiguration<SysDepartment>
    {
        public void Configure(EntityTypeBuilder<SysDepartment> entity)
        {
            entity.HasKey(e => e.No).HasName("PRIMARY");

            entity.Property(e => e.No).HasComment("流水號");
            entity.Property(e => e.CreateAt).HasComment("建立時間");
            entity.Property(e => e.CreateBy).HasComment("建立者");
            entity.Property(e => e.DeleteAt).HasComment("刪除");
            entity.Property(e => e.Id).HasComment("部門ID");
            entity.Property(e => e.IsEnabled).HasComment("啟用");
            entity.Property(e => e.Name).HasComment("名稱");
            entity.Property(e => e.Parent).HasComment("父部門ID");
            entity.Property(e => e.Sequence).HasComment("排列順序");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SysDepartment> entity);
    }
}
