// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class SysMenuConfiguration : IEntityTypeConfiguration<SysMenu>
    {
        public void Configure(EntityTypeBuilder<SysMenu> entity)
        {
            entity.HasKey(e => e.No).HasName("PRIMARY");

            entity.Property(e => e.No)
                .ValueGeneratedNever()
                .HasComment("流水號");
            entity.Property(e => e.Action).HasComment("Action");
            entity.Property(e => e.Controller).HasComment("Controller");
            entity.Property(e => e.DeleteAt).HasComment("刪除");
            entity.Property(e => e.Description).HasComment("描述");
            entity.Property(e => e.Enabled).HasComment("啟用");
            entity.Property(e => e.Id).HasComment("選單ID");
            entity.Property(e => e.Name).HasComment("名稱");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SysMenu> entity);
    }
}
