// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class SysRoomConfiguration : IEntityTypeConfiguration<SysRoom>
    {
        public void Configure(EntityTypeBuilder<SysRoom> entity)
        {
            entity.HasKey(e => e.No).HasName("PRIMARY");

            entity.Property(e => e.No).HasComment("流水號");
            entity.Property(e => e.CreateAt).HasComment("建立時間");
            entity.Property(e => e.CreateBy).HasComment("建立者");
            entity.Property(e => e.DeleteAt).HasComment("刪除");
            entity.Property(e => e.Description).HasComment("描述");
            entity.Property(e => e.Floor).HasComment("樓層");
            entity.Property(e => e.Id).HasComment("會議室ID");
            entity.Property(e => e.IsEnabled).HasComment("啟用");
            entity.Property(e => e.Name).HasComment("名稱");
            entity.Property(e => e.RealSeat)
                .HasDefaultValueSql("'0'")
                .HasComment("是否啟用實體座位");
            entity.Property(e => e.Type).HasComment("類型 (1:實體 2:虛擬)");
            entity.Property(e => e.VirtualSeat)
                .HasDefaultValueSql("'0'")
                .HasComment("是否啟用虛擬座位");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SysRoom> entity);
    }
}
