// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class SysRoomConfiguration : IEntityTypeConfiguration<SysRoom>
    {
        public void Configure(EntityTypeBuilder<SysRoom> entity)
        {
            entity.HasKey(e => e.No).HasName("PRIMARY");

            entity.Property(e => e.No).HasComment("流水號");
            entity.Property(e => e.Id).HasComment("會議室ID");
            entity.Property(e => e.Name).HasComment("名稱");
            entity.Property(e => e.Building).HasComment("樓棟名稱");
            entity.Property(e => e.Floor).HasComment("樓層");
            entity.Property(e => e.Description).HasComment("描述");
            entity.Property(e => e.IsEnabled).HasComment("啟用");
            entity.Property(e => e.CreateAt).HasComment("建立時間");
            entity.Property(e => e.CreateBy).HasComment("建立者");
            entity.Property(e => e.DeleteAt).HasComment("刪除");

            entity.Property(e => e.Capacity)
                .HasDefaultValue(0)
                .HasComment("容納人數");
            entity.Property(e => e.Area)
                .HasDefaultValue(0)
                .HasComment("面積(平方公尺)");
            entity.Property(e => e.Number).HasComment("房間編號");
            entity.Property(e => e.Image).HasComment("會議室圖片URL");
            entity.Property(e => e.Status)
                .HasDefaultValue("available")
                .HasComment("使用狀態(available/occupied/maintenance)");
            entity.Property(e => e.PricingType)
                .HasDefaultValue("hourly")
                .HasComment("收費方式(hourly/period)");
            entity.Property(e => e.BookingSettings).HasComment("租借權限設定");

            OnConfigurePartial(entity);
        }
        partial void OnConfigurePartial(EntityTypeBuilder<SysRoom> entity);
    }
}
