// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class SysRoomPricePeriodConfiguration : IEntityTypeConfiguration<SysRoomPricePeriod>
    {
        public void Configure(EntityTypeBuilder<SysRoomPricePeriod> entity)
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");  // ✅ 改成用 Id 當主鍵

            entity.HasIndex(e => e.RoomId, "RoomId");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()  // ✅ Id 自動產生
                .HasComment("記錄ID");

            entity.Property(e => e.RoomId).HasComment("會議室ID");
            entity.Property(e => e.Name).HasComment("時段名稱");
            entity.Property(e => e.StartTime).HasComment("開始時間");
            entity.Property(e => e.EndTime).HasComment("結束時間");
            entity.Property(e => e.Price)
                .HasDefaultValue(0)
                .HasComment("價格");
            entity.Property(e => e.IsEnabled)
                .HasDefaultValue(true)
                .HasComment("是否開放");
            entity.Property(e => e.CreateAt).HasComment("建立時間");
            entity.Property(e => e.CreateBy).HasComment("建立者");
            entity.Property(e => e.DeleteAt).HasComment("刪除時間");
            entity.Property(e => e.SetupPrice)
                .HasColumnType("decimal(10,2)")
                .HasComment("場布價格");

            entity.HasOne(d => d.Room)
                .WithMany(p => p.SysRoomPricePeriod)
                .HasForeignKey(d => d.RoomId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_SysRoomPricePeriod_SysRoom");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SysRoomPricePeriod> entity);
    }
}