// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class VisitorConfiguration : IEntityTypeConfiguration<Visitor>
    {
        public void Configure(EntityTypeBuilder<Visitor> entity)
        {
            entity.HasKey(e => e.No).HasName("PRIMARY");

            entity.HasIndex(e => e.CreatedBy, "CreatedBy");
            entity.HasIndex(e => e.Id, "Id").IsUnique();

            entity.Property(e => e.No).HasComment("流水號");
            entity.Property(e => e.Id).HasComment("訪客ID");
            entity.Property(e => e.CName).HasComment("中文名稱");
            entity.Property(e => e.EName).HasComment("英文名稱");
            entity.Property(e => e.CompanyName).HasComment("公司名稱");
            entity.Property(e => e.JobTitle).HasComment("職位");
            entity.Property(e => e.Phone).HasComment("電話");
            entity.Property(e => e.Email).HasComment("電子郵件");
            entity.Property(e => e.LicensePlate).HasComment("車牌號碼");
            entity.Property(e => e.CarType).HasComment("車型");

            entity.Property(e => e.CheckInAt).HasComment("簽到時間");
            entity.Property(e => e.CheckOutAt).HasComment("簽出時間");
            entity.Property(e => e.IsEnabled)
                .HasDefaultValueSql("1")
                .HasComment("是否啟用");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("current_timestamp()")
                .HasComment("建立時間");
            entity.Property(e => e.CreatedBy).HasComment("建立者");
            entity.Property(e => e.UpdatedAt).HasComment("更新時間");
            entity.Property(e => e.UpdatedBy).HasComment("更新者");
            entity.Property(e => e.DeleteAt).HasComment("刪除時間");

            entity.HasOne(d => d.CreatedByNavigation)
                .WithMany(p => p.VisitorCreatedBy)
                .HasPrincipalKey(p => p.Id)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("Visitor_ibfk_2");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Visitor> entity);
    }
}