// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TASA.Models;

namespace TASA.Models.Configurations
{
    public partial class WebexConfiguration : IEntityTypeConfiguration<Webex>
    {
        public void Configure(EntityTypeBuilder<Webex> entity)
        {
            entity.HasKey(e => e.No).HasName("PRIMARY");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Webex> entity);
    }
}
