// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

[Index("UserId", Name = "UserId")]
public partial class AuthForget
{
    /// <summary>
    /// 流水號
    /// </summary>
    [Key]
    [Column(TypeName = "int(10) unsigned")]
    public uint No { get; set; }

    /// <summary>
    /// 忘記密碼ID
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// 使用者ID
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// 有效時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime ExpiresAt { get; set; }

    /// <summary>
    /// 是否使用
    /// </summary>
    public bool IsUsed { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("AuthForget")]
    public virtual AuthUser User { get; set; }
}