// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

[Index("DepartmentId", Name = "AuthUser_ibfk_1")]
[Index("Id", Name = "Id", IsUnique = true)]
public partial class AuthUser
{
    /// <summary>
    /// 流水號
    /// </summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Column(TypeName = "int(10) unsigned")]
    public uint No { get; set; }

    /// <summary>
    /// 使用者ID	
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// 名稱
    /// </summary>
    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    /// <summary>
    /// 帳號
    /// </summary>
    [Required]
    [StringLength(50)]
    public string Account { get; set; }

    /// <summary>
    /// 密碼
    /// </summary>
    [StringLength(50)]
    public string Password { get; set; }

    /// <summary>
    /// 密碼雜湊
    /// </summary>
    [Required]
    [StringLength(400)]
    public string PasswordHash { get; set; }

    /// <summary>
    /// 密碼鹽值
    /// </summary>
    [Required]
    [StringLength(100)]
    public string PasswordSalt { get; set; }

    /// <summary>
    /// 電子信箱	
    /// </summary>
    [StringLength(100)]
    public string Email { get; set; }

    /// <summary>
    /// 卡號
    /// </summary>
    [StringLength(50)]
    public string Card { get; set; }

    /// <summary>
    /// 單位
    /// </summary>
    public Guid? DepartmentId { get; set; }

    /// <summary>
    /// 啟用
    /// </summary>
    public bool IsEnabled { get; set; }

    /// <summary>
    /// 已審核
    /// </summary>
    public bool IsApproved { get; set; }

    /// <summary>
    /// 建立時間	
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime CreateAt { get; set; }

    public Guid CreateBy { get; set; }

    /// <summary>
    /// 刪除
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? DeleteAt { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<AuthForget> AuthForget { get; set; } = new List<AuthForget>();

    [InverseProperty("CreateByNavigation")]
    public virtual ICollection<Conference> Conference { get; set; } = new List<Conference>();

    [InverseProperty("User")]
    public virtual ICollection<ConferenceTemplateUser> ConferenceTemplateUser { get; set; } = new List<ConferenceTemplateUser>();

    [InverseProperty("User")]
    public virtual ICollection<ConferenceUser> ConferenceUser { get; set; } = new List<ConferenceUser>();

    // ✅ 加入這行
    [InverseProperty("CreateByNavigation")]
    public virtual ICollection<SeatSettings> SeatSetting { get; set; } = new List<SeatSettings>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<Visitor> VisitorCreatedBy { get; set; } = new List<Visitor>();


    [ForeignKey("DepartmentId")]
    [InverseProperty("AuthUser")]
    public virtual SysDepartment Department { get; set; }

    [ForeignKey("AuthUserId")]
    [InverseProperty("AuthUser")]
    public virtual ICollection<AuthRole> AuthRole { get; set; } = new List<AuthRole>();

    [InverseProperty("UploadedByNavigation")]
    public virtual ICollection<ConferencePaymentProof> ConferencePaymentProofUploadedBy { get; set; } = new List<ConferencePaymentProof>();

    [InverseProperty("ReviewedByNavigation")]
    public virtual ICollection<ConferencePaymentProof> ConferencePaymentProofReviewedBy { get; set; } = new List<ConferencePaymentProof>();
}