// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

[Index("Id", Name = "Id", IsUnique = true)]
public partial class AuthRole
{
    /// <summary>
    /// 流水號
    /// </summary>
    [Key]
    [Column(TypeName = "int(10) unsigned")]
    public uint No { get; set; }

    /// <summary>
    /// 角色ID
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// 角色名稱
    /// </summary>
    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    /// <summary>
    /// 是否全域
    /// </summary>
    public bool Global { get; set; }

    /// <summary>
    /// 角色代碼
    /// </summary>
    [StringLength(20)]
    public string Code { get; set; }

    /// <summary>
    /// 啟用
    /// </summary>
    public bool IsEnabled { get; set; }

    /// <summary>
    /// 刪除
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? DeleteAt { get; set; }

    [ForeignKey("AuthRoleId")]
    [InverseProperty("AuthRole")]
    public virtual ICollection<AuthUser> AuthUser { get; set; } = new List<AuthUser>();

    [ForeignKey("AuthRoleId")]
    [InverseProperty("AuthRole")]
    public virtual ICollection<SysMenu> SysMenu { get; set; } = new List<SysMenu>();
}