// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

[PrimaryKey("ConferenceId", "UserId")]
[Index("UserId", Name = "ConferencesUsers_ibfk_2")]
public partial class ConferenceUser
{
    /// <summary>
    /// 會議ID
    /// </summary>
    [Key]
    public Guid ConferenceId { get; set; }

    /// <summary>
    /// 使用者ID
    /// </summary>
    [Key]
    public Guid UserId { get; set; }

    /// <summary>
    /// 與會人員
    /// </summary>
    public bool IsAttendees { get; set; }

    /// <summary>
    /// 主持人
    /// </summary>
    public bool IsHost { get; set; }

    /// <summary>
    /// 會議記錄
    /// </summary>
    public bool IsRecorder { get; set; }

    [ForeignKey("ConferenceId")]
    [InverseProperty("ConferenceUser")]
    public virtual Conference Conference { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("ConferenceUser")]
    public virtual AuthUser User { get; set; }
}