// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using TASA.Models.Enums;

namespace TASA.Models;

[Index("CreateBy", Name = "CreatedBy")]
[Index("Id", Name = "Id", IsUnique = true)]
[Index("Status", Name = "Status")]
[Index("ReservationStatus", "CreateAt", Name = "idx_reservation_status")] // ✅ 新增索引
public partial class Conference
{
    /// <summary>
    /// 流水號
    /// </summary>
    [Key]
    [Column(TypeName = "int(10) unsigned")]
    public uint No { get; set; }

    /// <summary>
    /// 會議ID
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// 名稱
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    /// <summary>
    /// 會議種類 (1:一般 2:視訊)
    /// </summary>
    [Column(TypeName = "tinyint(1) unsigned")]
    public byte UsageType { get; set; }

    /// <summary>
    /// 連線選項
    /// </summary>
    [Column(TypeName = "tinyint(1) unsigned")]
    public byte? MCU { get; set; }

    /// <summary>
    /// 錄製
    /// </summary>
    public bool Recording { get; set; }

    /// <summary>
    /// 會議內容
    /// </summary>
    [Column(TypeName = "text")]
    public string Description { get; set; }

    /// <summary>
    /// 開始時間 (由 ConferenceRoomSlot 決定，可為 NULL)
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? StartTime { get; set; } // ✅ 改為 nullable

    /// <summary>
    /// 結束時間 (由 ConferenceRoomSlot 決定，可為 NULL)
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? EndTime { get; set; } // ✅ 改為 nullable

    /// <summary>
    /// 實際結束時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? FinishTime { get; set; }

    /// <summary>
    /// 持續時間(小時)
    /// </summary>
    [Column(TypeName = "tinyint(2) unsigned")]
    public byte DurationHH { get; set; }

    /// <summary>
    /// 持續時間(分鐘)
    /// </summary>
    [Column(TypeName = "tinyint(2) unsigned")]
    public byte DurationSS { get; set; }

    /// <summary>
    /// 重複會議父ID
    /// </summary>
    public Guid? RecurrenceId { get; set; }

    /// <summary>
    /// 重複(RFC5545)
    /// </summary>
    [StringLength(200)]
    public string RRule { get; set; }

    /// <summary>
    /// 電子郵件通知信箱群
    /// </summary>
    [Column(TypeName = "text")]
    public string Email { get; set; }

    /// <summary>
    /// 狀態 (會議進行狀態：未開始、進行中、已結束等)
    /// </summary>
    [Column(TypeName = "tinyint(1) unsigned")]
    public byte? Status { get; set; }

    /// <summary>
    /// 預約狀態 (0=已釋放, 1=待審核, 2=待繳費, 3=預約成功, 4=審核拒絕)- ✅ 新增
    /// </summary>
    [Column(TypeName = "tinyint(1) unsigned")]
    public ReservationStatus ReservationStatus { get; set; } = ReservationStatus.PendingApproval;


    /// <summary>
    /// ✅ 新增：拒絕原因
    /// </summary>
    [Column(TypeName = "text")]
    public string RejectReason { get; set; }

    /// <summary>
    /// 審核時間 - ✅ 新增
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? ReviewedAt { get; set; }

    /// <summary>
    /// 審核者 - ✅ 新增
    /// </summary>
    public Guid? ReviewedBy { get; set; }

    /// <summary>
    /// 批准時間 - ✅ 新增
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? ApprovedAt { get; set; }

    /// <summary>
    /// 繳費期限 - ✅ 新增
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? PaymentDeadline { get; set; }

    /// <summary>
    /// 繳費提醒發送時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? PaymentReminderSentAt { get; set; }

    /// <summary>
    /// 報到時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? CheckinAt { get; set; }

    /// <summary>
    /// 報到者
    /// </summary>
    public Guid? CheckinBy { get; set; }

    /// <summary>
    /// 協助報到者
    /// </summary>
    public Guid? AgentBy { get; set; }

    /// <summary>
    /// 付費方式
    /// </summary>
    [Required]
    [StringLength(50)]
    public string PaymentMethod { get; set; }

    /// <summary>
    /// 付款狀態 (1=未付款, 2=待查帳 (已上傳憑證), 3= 已收款(全額), 4 = 已收款(訂金30%) , 5 = 已收款(尾款70%))
    /// </summary>
    [Column(TypeName = "int(11)")]
    public PaymentStatus PaymentStatus { get; set; } = PaymentStatus.Unpaid;

    /// <summary>
    /// 付款備註
    /// </summary>
    [StringLength(255)]
    public string PaymentNote { get; set; }

    /// <summary>
    /// 付款日期
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? PaidAt { get; set; }

    /// <summary>
    /// 部門代碼
    /// </summary>
    [StringLength(50)]
    public string DepartmentCode { get; set; }

    /// <summary>
    /// 會議室費用
    /// </summary>
    [Column(TypeName = "int(11)")]
    public int RoomCost { get; set; } = 0;

    /// <summary>
    /// 設備費用
    /// </summary>
    [Column(TypeName = "int(11)")]
    public int EquipmentCost { get; set; } = 0;

    /// <summary>
    /// 攤位費用
    /// </summary>
    [Column(TypeName = "int(11)")]
    public int BoothCost { get; set; } = 0;

    /// <summary>
    /// 總金額
    /// </summary>
    [Column(TypeName = "int(11)")]
    public int TotalAmount { get; set; } = 0;

    /// <summary>
    /// 折扣金額
    /// </summary>
    [Column(TypeName = "int(11)")]
    public int? DiscountAmount { get; set; }

    /// <summary>
    /// 折扣原因
    /// </summary>
    [Column(TypeName = "text")]
    public string? DiscountReason { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime CreateAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }
    /// <summary>
    /// 建立者
    /// </summary>
    public Guid CreateBy { get; set; }


    /// <summary>
    /// 刪除
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? DeleteAt { get; set; }

    /// <summary>
    /// 取消時間
    /// </summary>
    public DateTime? CancelledAt { get; set; }

    /// <summary>
    /// 取消者
    /// </summary>
    public Guid? CancelledBy { get; set; }

    /// <summary>
    /// 分院ID
    /// </summary>
    public Guid? DepartmentId { get; set; }

    /// <summary>
    /// 承辦單位
    /// </summary>
    [StringLength(100)]
    public string OrganizerUnit { get; set; }

    /// <summary>
    /// 會議主席
    /// </summary>
    [StringLength(100)]
    public string Chairman { get; set; }

    /* ===============================
     * Navigation Properties
     * =============================== */

    [InverseProperty("Conference")]
    public virtual ICollection<ConferenceUser> ConferenceUser { get; set; } = new List<ConferenceUser>();

    [InverseProperty("Conferences")]
    public virtual ConferenceWebex ConferenceWebex { get; set; }

    [ForeignKey("CreateBy")]
    [InverseProperty("Conference")]
    public virtual AuthUser CreateByNavigation { get; set; }

    [InverseProperty("Conference")]
    public virtual ICollection<LogWebex> LogWebex { get; set; } = new List<LogWebex>();

    [ForeignKey("Status")]
    [InverseProperty("Conference")]
    public virtual ConferenceStatus StatusNavigation { get; set; }

    [ForeignKey("ConferenceId")]
    [InverseProperty("Conference")]
    public virtual ICollection<SysDepartment> Department { get; set; } = new List<SysDepartment>();

    [ForeignKey("ConferenceId")]
    [InverseProperty("Conference")]
    public virtual ICollection<Ecs> Ecs { get; set; } = new List<Ecs>();

    [ForeignKey("ConferenceId")]
    [InverseProperty("Conference")]
    public virtual ICollection<SysRoom> Room { get; set; } = new List<SysRoom>();

    // ✅ 如果有 Navigation Property,也可以加上:
    public virtual AuthUser? CancelledByNavigation { get; set; }

    [InverseProperty("Conference")]
    public virtual ICollection<ConferenceVisitor> ConferenceVisitors { get; set; } = new List<ConferenceVisitor>();

    [InverseProperty("Conference")]
    public virtual ICollection<ConferenceEquipment> ConferenceEquipments { get; set; } = new List<ConferenceEquipment>();

    // ✅ 新增：時段關聯
    [InverseProperty("Conference")]
    public virtual ICollection<ConferenceRoomSlot> ConferenceRoomSlots { get; set; } = new List<ConferenceRoomSlot>();

    // ✅ 新增：付款憑證關聯
    [InverseProperty("Conference")]
    public virtual ICollection<ConferencePaymentProof> ConferencePaymentProofs { get; set; } = new List<ConferencePaymentProof>();

    public virtual ICollection<ConferenceAttachment> Attachments { get; set; } = new List<ConferenceAttachment>();

}