// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

[Index("ConferenceId", Name = "idx_conference_id")]
[Index("Status", Name = "idx_status")]
[Index("UploadedBy", Name = "idx_uploaded_by")]
[Index("ReviewedBy", Name = "idx_reviewed_by")]
[Index("Id", Name = "Id", IsUnique = true)]
public partial class ConferencePaymentProof
{


    /// <summary>
    /// 憑證ID
    /// </summary>
    [Key]
    public Guid Id { get; set; }

    /// <summary>
    /// 會議ID
    /// </summary>
    public Guid ConferenceId { get; set; }

    /// <summary>
    /// 檔案路徑
    /// </summary>
    [Required]
    [StringLength(500)]
    public string FilePath { get; set; }

    /// <summary>
    /// 檔案名稱
    /// </summary>
    [Required]
    [StringLength(255)]
    public string FileName { get; set; }

    /// <summary>
    /// 付款方式 (臨櫃/匯款)
    /// </summary>
    [StringLength(50)]
    public string PaymentType { get; set; }

    /// <summary>
    /// 轉帳末五碼
    /// </summary>
    [StringLength(5)]
    public string LastFiveDigits { get; set; }

    /// <summary>
    /// 轉帳金額
    /// </summary>
    [Column(TypeName = "int(11)")]
    public int? TransferAmount { get; set; }

    /// <summary>
    /// 轉帳時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? TransferAt { get; set; }

    /// <summary>
    /// 備註
    /// </summary>
    [Column(TypeName = "text")]
    public string Note { get; set; }

    /// <summary>
    /// 審核狀態 1 = 未付款 2 = 待查帳 (已上傳憑證)3 = 已收款(全額)4 = 已收款(訂金30%)5 = 已收款(尾款70%)
    /// </summary>
    [Column(TypeName = "tinyint(1) unsigned")]
    public byte Status { get; set; } = 0;

    /// <summary>
    /// 退回原因
    /// </summary>
    [Column(TypeName = "text")]
    public string RejectReason { get; set; }

    /// <summary>
    /// 上傳時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime UploadedAt { get; set; }

    /// <summary>
    /// 上傳者
    /// </summary>
    public Guid UploadedBy { get; set; }

    /// <summary>
    /// 審核時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? ReviewedAt { get; set; }

    /// <summary>
    /// 審核者
    /// </summary>
    public Guid? ReviewedBy { get; set; }

    /// <summary>
    /// 刪除時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? DeleteAt { get; set; }

    /* ===============================
     * Navigation Properties
     * =============================== */

    [ForeignKey("ConferenceId")]
    [InverseProperty("ConferencePaymentProofs")]
    public virtual Conference Conference { get; set; }

    [ForeignKey("UploadedBy")]
    [InverseProperty("ConferencePaymentProofUploadedBy")]
    public virtual AuthUser UploadedByNavigation { get; set; }

    [ForeignKey("ReviewedBy")]
    [InverseProperty("ConferencePaymentProofReviewedBy")]
    public virtual AuthUser ReviewedByNavigation { get; set; }
}