// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

public partial class ConferenceStatus
{
    /// <summary>
    /// 狀態
    /// </summary>
    [Key]
    [Column(TypeName = "tinyint(1) unsigned")]
    public byte No { get; set; }

    /// <summary>
    /// 描述
    /// </summary>
    [Required]
    [StringLength(20)]
    public string Description { get; set; }

    [InverseProperty("StatusNavigation")]
    public virtual ICollection<Conference> Conference { get; set; } = new List<Conference>();
}