// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

[Index("WebexId", Name = "ConferenceWebex_ibfk_2")]
public partial class ConferenceWebex
{
    /// <summary>
    /// UCMS會議ID
    /// </summary>
    [Key]
    public Guid ConferencesId { get; set; }

    /// <summary>
    /// Webex
    /// </summary>
    public Guid WebexId { get; set; }

    /// <summary>
    /// meetingId
    /// </summary>
    [Required]
    [StringLength(50)]
    public string Id { get; set; }

    /// <summary>
    /// 會議號碼
    /// </summary>
    [Required]
    [StringLength(50)]
    public string MeetingNumber { get; set; }

    /// <summary>
    /// 會議密碼
    /// </summary>
    [Required]
    [StringLength(50)]
    public string Password { get; set; }

    /// <summary>
    /// 會議連結
    /// </summary>
    [Required]
    [StringLength(200)]
    public string WebLink { get; set; }

    /// <summary>
    /// 主持人金鑰
    /// </summary>
    [Required]
    [StringLength(50)]
    public string HostKey { get; set; }

    /// <summary>
    /// 撥入號碼
    /// </summary>
    [Required]
    [StringLength(50)]
    public string CallInNumber { get; set; }

    /// <summary>
    /// SIP
    /// </summary>
    [Required]
    [StringLength(100)]
    public string SipAddress { get; set; }

    /// <summary>
    /// 刪除
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? DeleteAt { get; set; }

    [ForeignKey("ConferencesId")]
    [InverseProperty("ConferenceWebex")]
    public virtual Conference Conferences { get; set; }

    [ForeignKey("WebexId")]
    [InverseProperty("ConferenceWebex")]
    public virtual Webex Webex { get; set; }
}