// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

[Index("ConferenceId", Name = "idx_conference")]
public partial class ConferenceEquipment
{
    /// <summary>
    /// ID
    /// </summary>
    [Key]
    [Column(TypeName = "char(36)")]
    public Guid Id { get; set; }

    /// <summary>
    /// 會議ID
    /// </summary>
    [Required]
    [Column(TypeName = "char(36)")]
    public Guid ConferenceId { get; set; }

    /// <summary>
    /// 設備ID (包含攤位)
    /// </summary>
    [Required]
    [Column(TypeName = "char(36)")]
    public Guid EquipmentId { get; set; }

    /// <summary>
    /// 類型 1=設備 2=攤位
    /// </summary>
    [StringLength(1)]
    public string EquipmentType { get; set; }

    /// <summary>
    /// 設備名稱快照
    /// </summary>
    [Required]
    [StringLength(100)]
    public string EquipmentName { get; set; }

    /// <summary>
    /// 設備價格快照
    /// </summary>
    [Column(TypeName = "int(11)")]
    public int EquipmentPrice { get; set; } = 0;

    /// <summary>
    /// 建立時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    // Navigation Properties

    /// <summary>
    /// 關聯的會議
    /// </summary>
    [ForeignKey("ConferenceId")]
    [InverseProperty("ConferenceEquipments")]
    public virtual Conference Conference { get; set; }
}