// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

[Index("VisitorId", Name = "FK_ConferenceVisitor_Visitor")]
public partial class ConferenceVisitor
{
    /// <summary>
    /// 會議ID
    /// </summary>
    [Key]
    [Column(Order = 0)]
    public Guid ConferenceId { get; set; }

    /// <summary>
    /// 訪客ID
    /// </summary>
    [Key]
    [Column(Order = 1)]
    public Guid VisitorId { get; set; }

    [ForeignKey("ConferenceId")]
    [InverseProperty("ConferenceVisitors")]
    public virtual Conference Conference { get; set; }

    [ForeignKey("VisitorId")]
    [InverseProperty("ConferenceVisitors")]
    public virtual Visitor Visitor { get; set; }
}