// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

[Index("CreateBy", Name = "CreatedBy")]
[Index("Id", Name = "Id", IsUnique = true)]
public partial class ConferenceTemplate
{
    /// <summary>
    /// 流水號
    /// </summary>
    [Key]
    [Column(TypeName = "int(10) unsigned")]
    public uint No { get; set; }

    /// <summary>
    /// 會議ID
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// 名稱
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    /// <summary>
    /// 會議種類 (1:一般 2:視訊)
    /// </summary>
    [Column(TypeName = "tinyint(1) unsigned")]
    public byte UsageType { get; set; }

    /// <summary>
    /// 連線選項
    /// </summary>
    [Column(TypeName = "tinyint(1) unsigned")]
    public byte? MCU { get; set; }

    /// <summary>
    /// 錄製
    /// </summary>
    public bool Recording { get; set; }

    /// <summary>
    /// 會議內容
    /// </summary>
    [Column(TypeName = "text")]
    public string Description { get; set; }

    /// <summary>
    /// 持續時間(小時)
    /// </summary>
    [Column(TypeName = "tinyint(2) unsigned")]
    public byte DurationHH { get; set; }

    /// <summary>
    /// 持續時間(分鐘)
    /// </summary>
    [Column(TypeName = "tinyint(2) unsigned")]
    public byte DurationSS { get; set; }

    /// <summary>
    /// 重複(RFC5545)
    /// </summary>
    [StringLength(200)]
    public string RRule { get; set; }

    /// <summary>
    /// 電子郵件通知信箱群
    /// </summary>
    [Column(TypeName = "text")]
    public string Email { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime CreateAt { get; set; }

    /// <summary>
    /// 建立者
    /// </summary>
    public Guid CreateBy { get; set; }

    public Guid? DepartmentId { get; set; }

    /// <summary>
    /// 刪除
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? DeleteAt { get; set; }

    [InverseProperty("Conference")]
    public virtual ICollection<ConferenceTemplateUser> ConferenceTemplateUser { get; set; } = new List<ConferenceTemplateUser>();

    [ForeignKey("ConferenceId")]
    [InverseProperty("ConferenceNavigation")]
    public virtual ICollection<SysDepartment> Department { get; set; } = new List<SysDepartment>();

    [ForeignKey("ConferenceId")]
    [InverseProperty("ConferenceNavigation")]
    public virtual ICollection<SysRoom> Room { get; set; } = new List<SysRoom>();
}