// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

[Index("Id", Name = "Id", IsUnique = true)]
[Index("RoomId", Name = "RoomId")]
public partial class Ecs
{
    /// <summary>
    /// 流水號
    /// </summary>
    [Key]
    [Column(TypeName = "int(10) unsigned")]
    public uint No { get; set; }

    /// <summary>
    /// 情境ID
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// 名稱
    /// </summary>
    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    /// <summary>
    /// 會議室ID
    /// </summary>
    public Guid RoomId { get; set; }

    /// <summary>
    /// 指令
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Macro { get; set; }

    /// <summary>
    /// 啟用
    /// </summary>
    public bool IsEnabled { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime CreateAt { get; set; }

    /// <summary>
    /// 建立者
    /// </summary>
    public Guid CreateBy { get; set; }

    /// <summary>
    /// 刪除時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? DeleteAt { get; set; }

    [ForeignKey("RoomId")]
    [InverseProperty("Ecs")]
    public virtual SysRoom Room { get; set; }

    [ForeignKey("EcsId")]
    [InverseProperty("Ecs")]
    public virtual ICollection<Conference> Conference { get; set; } = new List<Conference>();
}