// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

[PrimaryKey("EcsId", "EquipmentId")]
[Index("EquipmentId", Name = "EquipmentId")]
public partial class EcsEquipment
{
    /// <summary>
    /// 情境ID
    /// </summary>
    [Key]
    public Guid EcsId { get; set; }

    /// <summary>
    /// 設備ID
    /// </summary>
    [Key]
    public Guid EquipmentId { get; set; }
}