// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

public partial class EquipmentType
{
    /// <summary>
    /// 狀態
    /// </summary>
    [Key]
    [Column(TypeName = "tinyint(1) unsigned")]
    public byte No { get; set; }

    /// <summary>
    /// 描述
    /// </summary>
    [Required]
    [StringLength(50)]
    public string Descript { get; set; }

    [InverseProperty("TypeNavigation")]
    public virtual ICollection<Equipment> Equipment { get; set; } = new List<Equipment>();
}