// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

[Index("Id", Name = "Id", IsUnique = true)]
[Index("Type", Name = "Type")]
public partial class Equipment
{
    /// <summary>
    /// 流水號
    /// </summary>
    [Key]
    [Column(TypeName = "int(10)")]
    public int No { get; set; }

    /// <summary>
    /// 裝備ID
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// 名稱
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    /// <summary>
    /// 裝備類型
    /// </summary>
    [Column(TypeName = "tinyint(1) unsigned")]
    public byte Type { get; set; }

    /// <summary>
    /// 裝備位置
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Host { get; set; }

    /// <summary>
    /// Port
    /// </summary>
    [Column(TypeName = "int(11)")]
    public int? Port { get; set; }

    /// <summary>
    /// 帳號
    /// </summary>
    [StringLength(100)]
    public string Account { get; set; }

    /// <summary>
    /// 密碼
    /// </summary>
    [StringLength(100)]
    public string Password { get; set; }

    /// <summary>
    /// 啟用
    /// </summary>
    public bool IsEnabled { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime CreateAt { get; set; }

    /// <summary>
    /// 建立者
    /// </summary>
    public Guid CreateBy { get; set; }

    /// <summary>
    /// 刪除
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? DeleteAt { get; set; }

    [ForeignKey("Type")]
    [InverseProperty("Equipment")]
    public virtual EquipmentType TypeNavigation { get; set; }
}