// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

public partial class LogMail
{
    /// <summary>
    /// 流水號
    /// </summary>
    [Key]
    [Column(TypeName = "int(10)")]
    public int No { get; set; }

    /// <summary>
    /// 收件者
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Address { get; set; }

    /// <summary>
    /// SMTP PORT
    /// </summary>
    [Column(TypeName = "int(5)")]
    public int Port { get; set; }

    /// <summary>
    /// SMTP SSL
    /// </summary>
    public bool EnableSsl { get; set; }

    /// <summary>
    /// 觸發Class
    /// </summary>
    [Required]
    [StringLength(100)]
    public string ClassName { get; set; }

    /// <summary>
    /// 觸發Function
    /// </summary>
    [Required]
    [StringLength(100)]
    public string FunctionName { get; set; }

    /// <summary>
    /// 錯誤資訊
    /// </summary>
    [StringLength(500)]
    public string Exception { get; set; }

    /// <summary>
    /// 寄送時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime SendTime { get; set; }
}