// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

public partial class LogSys
{
    /// <summary>
    /// 流水號
    /// </summary>
    [Key]
    [Column(TypeName = "int(10) unsigned")]
    public uint No { get; set; }

    /// <summary>
    /// IP
    /// </summary>
    [Required]
    [StringLength(15)]
    public string Ip { get; set; }

    /// <summary>
    /// 時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime Time { get; set; }

    /// <summary>
    /// 類型
    /// </summary>
    [Required]
    [StringLength(20)]
    public string InfoType { get; set; }

    /// <summary>
    /// 訊息
    /// </summary>
    [Required]
    [StringLength(500)]
    public string Info { get; set; }

    /// <summary>
    /// 使用者ID
    /// </summary>
    public Guid? UserId { get; set; }

    /// <summary>
    /// 分院ID
    /// </summary>
    [Column(TypeName = "char(36)")]
    public Guid? DepartmentId { get; set; }
}