// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

[Index("ConferenceId", Name = "ConferenceId")]
public partial class LogWebex
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int No { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Time { get; set; }

    public Guid? ConferenceId { get; set; }

    [Required]
    [StringLength(500)]
    public string Exception { get; set; }

    [ForeignKey("ConferenceId")]
    [InverseProperty("LogWebex")]
    public virtual Conference Conference { get; set; }
}