// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

[Index("Id", Name = "Id", IsUnique = true)]
[Index("ConfigKey", Name = "ConfigKey", IsUnique = true)]
public partial class SysConfig
{
    /// <summary>
    /// 流水號
    /// </summary>
    [Key]
    [Column(TypeName = "int(10) unsigned")]
    public uint No { get; set; }

    /// <summary>
    /// 設定ID
    /// </summary>
    [Required]
    [StringLength(36)]
    public Guid Id { get; set; }

    /// <summary>
    /// 設定鍵
    /// </summary>
    [Required]
    [StringLength(100)]
    public string ConfigKey { get; set; }

    /// <summary>
    /// 設定值
    /// </summary>
    [Required]
    [StringLength(500)]
    public string ConfigValue { get; set; }

    /// <summary>
    /// 啟用
    /// </summary>
    public bool Enabled { get; set; } = true;

    /// <summary>
    /// 刪除時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? DeleteAt { get; set; }
}