// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

[Index("Id", Name = "Id", IsUnique = true)]
public partial class SysMenu
{
    /// <summary>
    /// 流水號
    /// </summary>
    [Key]
    [Column(TypeName = "int(10) unsigned")]
    public uint No { get; set; }

    /// <summary>
    /// 選單ID
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// 名稱
    /// </summary>
    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    /// <summary>
    /// Controller
    /// </summary>
    [Required]
    [StringLength(50)]
    public string Controller { get; set; }

    /// <summary>
    /// Action
    /// </summary>
    [Required]
    [StringLength(50)]
    public string Action { get; set; }

    /// <summary>
    /// 描述
    /// </summary>
    [MaxLength(100)]
    public byte[] Description { get; set; }

    /// <summary>
    /// 啟用
    /// </summary>
    public bool Enabled { get; set; }

    /// <summary>
    /// 刪除
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? DeleteAt { get; set; }

    [ForeignKey("SysMenuId")]
    [InverseProperty("SysMenu")]
    public virtual ICollection<AuthRole> AuthRole { get; set; } = new List<AuthRole>();
}