// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

[Index("Id", Name = "Id", IsUnique = true)]
[Index("RoomId", Name = "RoomId")]
public partial class SysRoomPricePeriod
{

    /// <summary>
    /// 記錄ID
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// 會議室ID
    /// </summary>
    public Guid RoomId { get; set; }

    /// <summary>
    /// 時段名稱
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    /// <summary>
    /// 開始時間
    /// </summary>
    [Column(TypeName = "time")]
    public TimeSpan StartTime { get; set; }

    /// <summary>
    /// 結束時間
    /// </summary>
    [Column(TypeName = "time")]
    public TimeSpan EndTime { get; set; }

    /// <summary>
    /// 價格 (平日)
    /// </summary>
    [Column(TypeName = "decimal(10,2)")]
    public decimal Price { get; set; }

    /// <summary>
    /// 假日價格
    /// </summary>
    [Column(TypeName = "decimal(10,2)")]
    public decimal? HolidayPrice { get; set; }

    /// <summary>
    /// 是否開放
    /// </summary>
    public bool IsEnabled { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime CreateAt { get; set; }

    /// <summary>
    /// 建立者
    /// </summary>
    public Guid CreateBy { get; set; }

    /// <summary>
    /// 刪除時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? DeleteAt { get; set; }

    [ForeignKey("RoomId")]
    [InverseProperty("SysRoomPricePeriod")]
    public virtual SysRoom Room { get; set; }
}