// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using TASA.Models.Enums;

namespace TASA.Models;

[Index("Id", Name = "Id", IsUnique = true)]
public partial class SysRoom
{
    /// <summary>
    /// 流水號
    /// </summary>
    [Key]
    [Column(TypeName = "int(10) unsigned")]
    public uint No { get; set; }

    /// <summary>
    /// 會議室ID
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// 名稱
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    /// <summary>
    /// 樓棟名稱
    /// </summary>
    [StringLength(100)]
    public string Building { get; set; }

    /// <summary>
    /// 樓層
    /// </summary>
    public string Floor { get; set; }

    /// <summary>
    /// 描述
    /// </summary>
    [Column(TypeName = "text")]
    public string Description { get; set; }

    /// <summary>
    /// 啟用
    /// </summary>
    public bool IsEnabled { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime CreateAt { get; set; }

    /// <summary>
    /// 建立者
    /// </summary>
    public Guid CreateBy { get; set; }

    /// <summary>
    /// 刪除
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? DeleteAt { get; set; }

    /// <summary>
    /// 容納人數
    /// </summary>
    [Column(TypeName = "int(10) unsigned")]
    public uint Capacity { get; set; }

    /// <summary>
    /// 面積(平方公尺)
    /// </summary>
    [Column(TypeName = "decimal(10,2)")]
    public decimal Area { get; set; }

    /// <summary>
    /// 使用狀態(available/maintenance)
    /// </summary>
    public RoomStatus Status { get; set; }

    /// <summary>
    /// 收費方式(hourly/period)
    /// </summary>
    public PricingType PricingType { get; set; }

    /// <summary>
    /// 租借權限設定
    /// </summary>
    public BookingSettings BookingSettings { get; set; }

    public Guid? DepartmentId { get; set; }

    public SysDepartment? Department { get; set; }

    /// <summary>
    /// 會議室管理者ID
    /// </summary>
    public Guid? ManagerId { get; set; }

    /// <summary>
    /// 會議室管理者
    /// </summary>
    [ForeignKey("ManagerId")]
    public virtual AuthUser? Manager { get; set; }

    /// <summary>
    /// 聲明書路徑（自訂聲明書，若無則使用公版）
    /// </summary>
    [StringLength(500)]
    public string? AgreementPath { get; set; }

    [InverseProperty("Room")]
    public virtual ICollection<Ecs> Ecs { get; set; } = new List<Ecs>();

    [ForeignKey("RoomId")]
    [InverseProperty("Room")]
    public virtual ICollection<Conference> Conference { get; set; } = new List<Conference>();

    [ForeignKey("RoomId")]
    [InverseProperty("Room")]
    public virtual ICollection<ConferenceTemplate> ConferenceNavigation { get; set; } = new List<ConferenceTemplate>();

    [InverseProperty("Room")]
    public virtual ICollection<SysRoomPriceHourly> SysRoomPriceHourly { get; set; } = new List<SysRoomPriceHourly>();

    [InverseProperty("Room")]
    public virtual ICollection<SysRoomPricePeriod> SysRoomPricePeriod { get; set; } = new List<SysRoomPricePeriod>();

    public virtual ICollection<SysRoomImage> Images { get; set; } = new List<SysRoomImage>();

    public virtual ICollection<Equipment> Equipment { get; set; } = new List<Equipment>();


}