// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models
{
    public class SysRoomImage
    {
        public Guid Id { get; set; }
        public Guid RoomId { get; set; }
        public string ImagePath { get; set; } = string.Empty;
        public string ImageName { get; set; } = string.Empty;
        public string FileType { get; set; } = "image";
        public int FileSize { get; set; }
        public int SortOrder { get; set; }
        public DateTime CreateAt { get; set; } = DateTime.Now;
        public Guid CreateBy { get; set; }

        public virtual SysRoom? Room { get; set; }
    }
}