// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

[Index("Id", Name = "Id", IsUnique = true)]
public partial class SysRoom
{
    /// <summary>
    /// 流水號
    /// </summary>
    [Key]
    [Column(TypeName = "int(10) unsigned")]
    public uint No { get; set; }

    /// <summary>
    /// 會議室ID
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// 名稱
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    /// <summary>
    /// 類型 (1:實體 2:虛擬)
    /// </summary>
    [Column(TypeName = "tinyint(1) unsigned")]
    public byte Type { get; set; }

    /// <summary>
    /// 樓層
    /// </summary>
    public bool? Floor { get; set; }

    /// <summary>
    /// 描述
    /// </summary>
    [Column(TypeName = "text")]
    public string Description { get; set; }

    /// <summary>
    /// 是否啟用實體座位
    /// </summary>
    public bool? RealSeat { get; set; }

    /// <summary>
    /// 是否啟用虛擬座位
    /// </summary>
    public bool? VirtualSeat { get; set; }

    /// <summary>
    /// 啟用
    /// </summary>
    public bool IsEnabled { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime CreateAt { get; set; }

    /// <summary>
    /// 建立者
    /// </summary>
    public Guid CreateBy { get; set; }

    /// <summary>
    /// 刪除
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? DeleteAt { get; set; }

    [InverseProperty("Room")]
    public virtual ICollection<Ecs> Ecs { get; set; } = new List<Ecs>();

    [ForeignKey("RoomId")]
    [InverseProperty("Room")]
    public virtual ICollection<Conference> Conference { get; set; } = new List<Conference>();

    [ForeignKey("RoomId")]
    [InverseProperty("Room")]
    public virtual ICollection<ConferenceTemplate> ConferenceNavigation { get; set; } = new List<ConferenceTemplate>();
}