// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using TASA.Models.Configurations;
#nullable disable

namespace TASA.Models;

public partial class TASAContext : DbContext
{
    public TASAContext(DbContextOptions<TASAContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AuthForget> AuthForget { get; set; }

    public virtual DbSet<AuthRole> AuthRole { get; set; }

    public virtual DbSet<AuthUser> AuthUser { get; set; }

    public virtual DbSet<Conference> Conference { get; set; }

    public virtual DbSet<ConferenceStatus> ConferenceStatus { get; set; }

    public virtual DbSet<ConferenceTemplate> ConferenceTemplate { get; set; }

    public virtual DbSet<ConferenceTemplateUser> ConferenceTemplateUser { get; set; }

    public virtual DbSet<ConferenceUser> ConferenceUser { get; set; }

    public virtual DbSet<ConferenceWebex> ConferenceWebex { get; set; }

    public virtual DbSet<Ecs> Ecs { get; set; }

    public virtual DbSet<EcsEquipment> EcsEquipment { get; set; }

    public virtual DbSet<Equipment> Equipment { get; set; }

    public virtual DbSet<EquipmentType> EquipmentType { get; set; }

    public virtual DbSet<LogBackground> LogBackground { get; set; }

    public virtual DbSet<LogMail> LogMail { get; set; }

    public virtual DbSet<LogSys> LogSys { get; set; }

    public virtual DbSet<LogWebex> LogWebex { get; set; }

    public virtual DbSet<SysDepartment> SysDepartment { get; set; }

    public virtual DbSet<SysMenu> SysMenu { get; set; }

    public virtual DbSet<SysRoom> SysRoom { get; set; }

    public virtual DbSet<Webex> Webex { get; set; }

    public virtual DbSet<SeatSettings> SeatSettings { get; set; }

    public virtual DbSet<Visitor> Visitor { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb3_general_ci")
            .HasCharSet("utf8mb3");

        modelBuilder.ApplyConfiguration(new Configurations.AuthForgetConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.AuthRoleConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.AuthUserConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ConferenceConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ConferenceStatusConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ConferenceTemplateConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ConferenceTemplateUserConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ConferenceUserConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ConferenceWebexConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EcsConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EcsEquipmentConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EquipmentConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EquipmentTypeConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LogBackgroundConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LogMailConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LogSysConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LogWebexConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SysDepartmentConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SysMenuConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SysRoomConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.WebexConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SeatSettingsConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.VisitorConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
