// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

[Index("CreatedBy", Name = "CreatedBy")]
[Index("Id", Name = "Id", IsUnique = true)]
public partial class Visitor
{
    /// <summary>
    /// 流水號
    /// </summary>
    [Key]
    [Column(TypeName = "bigint(20) unsigned")]
    public ulong No { get; set; }

    /// <summary>
    /// 訪客ID
    /// </summary>
    [Required]
    public Guid Id { get; set; }

    /// <summary>
    /// 中文名稱
    /// </summary>
    [Required]
    [StringLength(100)]
    public string CName { get; set; }

    /// <summary>
    /// 英文名稱
    /// </summary>
    [StringLength(100)]
    public string? EName { get; set; }

    /// <summary>
    /// 公司名稱
    /// </summary>
    [StringLength(100)]
    public string? CompanyName { get; set; }

    /// <summary>
    /// 職位
    /// </summary>
    [StringLength(100)]
    public string? JobTitle { get; set; }

    /// <summary>
    /// 電話
    /// </summary>
    [StringLength(20)]
    public string? Phone { get; set; }

    /// <summary>
    /// 電子郵件
    /// </summary>
    [StringLength(100)]
    public string? Email { get; set; }

    /// <summary>
    /// 車牌號碼
    /// </summary>
    [StringLength(20)]
    public string? LicensePlate { get; set; }

    /// <summary>
    /// 車型
    /// </summary>
    [StringLength(50)]
    public string? CarType { get; set; }


    /// <summary>
    /// 簽到時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? CheckInAt { get; set; }

    /// <summary>
    /// 簽出時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? CheckOutAt { get; set; }

    /// <summary>
    /// 是否啟用
    /// </summary>
    [Column(TypeName = "tinyint(1) unsigned")]
    public bool IsEnabled { get; set; } = true;

    /// <summary>
    /// 建立時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// 建立者
    /// </summary>
    public Guid? CreatedBy { get; set; }

    /// <summary>
    /// 更新時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// 更新者
    /// </summary>
    public Guid? UpdatedBy { get; set; }

    /// <summary>
    /// 刪除時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? DeleteAt { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("VisitorCreatedBy")]
    public virtual AuthUser? CreatedByNavigation { get; set; }

    [InverseProperty("Visitor")]
    public virtual ICollection<ConferenceVisitor> ConferenceVisitors { get; set; } = new List<ConferenceVisitor>();
}