// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TASA.Models;

[Index("Id", Name = "Id", IsUnique = true)]
public partial class Webex
{
    [Key]
    [Column(TypeName = "int(11)")]
    public int No { get; set; }

    public Guid Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [Required]
    [StringLength(200)]
    public string Client_id { get; set; }

    [Required]
    [StringLength(200)]
    public string Client_secret { get; set; }

    [Required]
    [StringLength(200)]
    public string Access_token { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Expires { get; set; }

    [Required]
    [StringLength(200)]
    public string Refresh_token { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Refresh_token_expires { get; set; }

    public bool IsEnabled { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateAt { get; set; }

    public Guid CreateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeleteAt { get; set; }

    [InverseProperty("Webex")]
    public virtual ICollection<ConferenceWebex> ConferenceWebex { get; set; } = new List<ConferenceWebex>();
}